FileVersion = 1

[Project]
Name = "yyjson-beef"
DefaultNamespace = "yyjson"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\yyjson_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\yyjson.lib"]
